---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by @casual_degenerate
--- DateTime: 5/20/2020 6:13 PM
---
print = function(...)
	local s = "cd/:\t"
	for _,v in pairs({...}) do
		local v = tostring(v)
		--if type(v) == "string" then --[[OUT THIS HOUSE AND STAY OUT!]]
			if v:lower() == "warn" then
				rconsoleprint("@@YELLOW@@")
				v=""
			end
			if v:lower() == "error" then
				rconsoleprint("@@RED@@")
				v=""
			end
			if v:lower() == "good" then
			    rconsoleprint("@@GREEN@@")
			    v=""
			end
		--end
		s = s..v.."\t"
	end
	rconsoleprint(s.."\n")
end
local JSOND = function(a)return game:GetService("HttpService"):JSONDecode(a)end
local JSONE = function(a)return game:GetService("HttpService"):JSONEncode(a)end
JSONB=function(jsn) --Thank you [NekO]
    local o=''local tc=0 local isSt=false local nc=false
    if type(jsn)~='string'then error('\8[jsonB]:Give Json As String.')else
      for i=1,jsn:len()do
        t=function()return('\t'):rep(tc)end
        local tchr=jsn:sub(i,i)if tchr=='"'or tchr=="'"then isSt=not isSt end
        if isSt==false then
          if tchr=='{'or tchr=='['then
            tc=tc+1 tchr=tchr..'\n'..t()
          elseif jsn:sub(i,i+1)=='},'or jsn:sub(i,i+1)=='],'then
            tc=tc-1 nc=true tchr='\n'..t()..jsn:sub(i,i+1)..'\n'..t()
          elseif jsn:sub(i,i+1)~='},'and jsn:sub(i,i+1)~='],'then
            if jsn:sub(i,i)=='}'or jsn:sub(i,i)==']'then
              tc=tc-1 tchr='\n'..t()..tchr..'\n'..t()
            end
          end
          if tchr==','then
            if jsn:sub(i-1,i)~='],'and jsn:sub(i-1,i)~='},'then
              if nc==true and jsn:sub(i-1,i+1)~='","' then
                nc=false
              else tchr=tchr..'\n'..t()end
            end
          end
          if nc==true and tchr==','then else o=o..tchr end
        else o=o..tchr
        end
      end
    end
    return o
  end
debug = false --State as true to show stuff in a file called DEBUG.txt to know extra info.
http={}
http.request = function(input)
	local h = syn.request({Url = input, Method = "GET"})
	if h.StatusCode == 404 then
		print(err,"error")
		return(h.StatusCode)
	elseif h.StatusCode ~= 200 then
		print(err,"warn")
		return(h.StatusCode)
	end
	return h
end

censors = { "18"; "69"; "88"; "r34"; "420"; "455"; "8008"; } --Why the hell am I still up rn. --[[Me in 11/29/2020 Why am I working on this again? Also, I think those are most of them that I would find with numbers.]]
function censor(a)
    for i,v in pairs(censors) do
        if a == v then
            return true --Something I did fucked this part up. Had to fix it after 10+ minutes of me wondering "WHY THE FUCK IS IT SKIPPING THE CHECK ACC PART WHEN IT'S NOT ON THE CENSOR LIST"!. Turns out that it was the wrong return statements... EDIT: WRONG IT WAS DOING IT'S JUST JUST TURNED OUT MY MATH.RANDOM() CHOSE A NUMBER WITH 69 IN IT! I HATE LIFE SO FUCKING MUCH RN!
        end
        if string.find(a, v) then
            return true
        end
    end
    return false
end
--https://auth.roblox.com/v1/usernames/validate?context=UsernameChange&username=sdsfd69fdg
Check = {
  Account = function(username) if debug then print('run check.account with '..tostring(username)) end
    --The function
    if not censor(username) then if debug then print("past censor") end
      local i = 0
      while i<10 do 
        local i = i+1
        local h = http.request("https://api.roblox.com/users/get-by-username?username=" .. username) --ROBLOX username API jiz
        if type(h) == "number" then
          appendfile("cd/Log.txt","\nhttps://api.roblox.com/users/get-by-username?username=" .. username.." is giving out "..tostring(h))
          rconsoleprint("Failed. "..i.."/10")
        elseif JSOND(h.Body).errorMessage then
          return false
        else
          return true
        end
      wait()end
      rconsoleprint("There was a sevier problem in the code. Report this to the owner. And check Logs.txt in the cd folder.")
      return false
    end
  end;
  Asset = function(userId,assetId)
      return http.request("https://api.roblox.com/ownership/hasasset?userId="..userId.."&assetId="..assetId)
  end;
  Robux = function()
      local body = http.request("https://api.roblox.com/currency/balance")
      return body
  end;
  Game = function(id) --Does not work.
      local body = http.request("https://games.roblox.com/v1/games/multiget-place-details?placeIds=" .. id)
      return body
  end;
  Outfits = function(id)
      local body = http.request("https://avatar.roblox.com/v1/users/"..id.."/outfits")
      return body
  end;

}
output = ""

local name = "uncommon#1" --#1 being what is indefinite in the name
local i = 0
while true do --This is to check if there is a file already named the same thing.
  if not isfile("cd/Usernames/"..name.."("..tostring(i)..")"..".txt") then
    rconsoleprint("File not created...\nCreating file!\n\n")
    writefile("cd/Usernames/"..name.."("..tostring(i)..")"..".txt","")
    fileName = (name.."("..tostring(i)..")")
    break
  else
    i=i+1
  end
end
repeat fwait() until isfile("cd/Usernames/"..fileName..".txt")
for i=0,200 do --You can come up with your own ways of making this if you'd like.
	local TEST_name = name:gsub("#1",i)
	if Check.Account(TEST_name) == false then
		print("Found",TEST_name,"good")
		appendfile("cd/Usernames/"..fileName..".txt",TEST_name.."-")
	else
	    print("Searching",TEST_name,"error")
	end
end

